/**
 * Drizzle client for Azure Database for PostgreSQL.
 * Server/Node runtime ONLY. Replaces the Supabase service_role client.
 *
 * Lazy-init via Proxy so a missing env var at module load does NOT crash every
 * route that imports this file — the error surfaces at first actual use, where
 * route-level try/catch can handle it (mirrors the old lib/supabase.ts pattern).
 *
 * Schema is generated by `drizzle-kit pull` into ./schema.ts — re-run after DB changes.
 */

import { drizzle, type PostgresJsDatabase } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "./schema";

export type DB = PostgresJsDatabase<typeof schema>;

let _db: DB | null = null;
let _sql: ReturnType<typeof postgres> | null = null;

function init(): DB {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("Missing DATABASE_URL in environment");
  // prepare:false → safe behind PgBouncer transaction-mode pooling.
  _sql = postgres(url, { prepare: false, ssl: "require" });
  _db = drizzle(_sql, { schema });
  return _db;
}

export const db = new Proxy({} as DB, {
  get(_target, prop) {
    if (!_db) init();
    return (_db as unknown as Record<string | symbol, unknown>)[prop];
  },
});

// Raw postgres.js handle for the rare case a route needs unparameterized SQL.
export function sqlClient() {
  if (!_sql) init();
  return _sql!;
}

export * as schema from "./schema";
